version: '3'
services:
    client:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./client:/usr/share/nginx/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    server_1:
        environment:
            - NODE_ENV=development
        working_dir: /app
        image: node
        volumes:
            - ./server:/app
        command: bash -c "npm i && node index.js"

    server_2:
        environment:
            - NODE_ENV=development
        working_dir: /app
        image: node
        volumes:
            - ./server:/app
        command: bash -c "npm i && node index.js"

    redis:
        image: 'bitnami/redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes

    mysql_database:
        image: mariadb:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
          - ./docker/database.sql:/docker-entrypoint-initdb.d/database.sql
        environment:
            MYSQL_ROOT_PASSWORD: testRootPassword