version: '3'
services:
    client:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./client:/usr/share/nginx/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    server:
        environment:
            - NODE_ENV=development
        working_dir: /app
        image: node
        ports:
            - 3030:3030
        volumes:
            - ./server:/app
        command: bash -c "npm i && node index.js"

    mysql_database:
        image: mariadb:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
          - 3307:3306
        volumes:
          - ./docker/database.sql:/docker-entrypoint-initdb.d/database.sql
        environment:
            MYSQL_ROOT_PASSWORD: testRootPassword