version: '3'
services:
    balancer:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    server_1:
        working_dir: /app
        image: node
        volumes:
            - ./app:/app
        command: bash -c "npm i && npm start '/socket/'"

    server_2:
        working_dir: /app
        image: node
        volumes:
            - ./app:/app
        command: bash -c "npm i && npm start '/socket/'"

    server_polling_1:
        working_dir: /app
        image: node
        volumes:
            - ./app:/app
        command: bash -c "npm i && npm start '/polling/'"

    server_polling_2:
        working_dir: /app
        image: node
        volumes:
            - ./app:/app
        command: bash -c "npm i && npm start '/polling/'"

    redis:
        image: 'bitnami/redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes

    mysql_database:
        image: mariadb:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
          - ./docker/database.sql:/docker-entrypoint-initdb.d/database.sql
        environment:
            MYSQL_ROOT_PASSWORD: testRootPassword